scdf:
  binder:
    type: rabbit
  server:
    image:
      repository: spring-scdf-docker-prod-local.usw1.packages.broadcom.com/p-scdf-for-kubernetes/scdf-pro-server
      tag: 1.6.4
    service:
      type: LoadBalancer
    env:
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_STREAMS_ENABLED
        value: "true"
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_TASKS_ENABLED
        value: "true"
      - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
        value: "true"
  skipper:
    image:
      repository: spring-scdf-docker-prod-local.usw1.packages.broadcom.com/p-scdf-for-kubernetes/scdf-pro-skipper
      tag: 1.6.4
  registry:
    secret:
      ref: "reg-creds-dev-registry"
