name: Schedule Snapshot Train Builds

on:
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, 2.11.x]
    steps:
    - uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Build Snapshot Controller
        token: ${{ secrets.SCDF_ACCESS_TOKEN }}
        ref: ${{ matrix.branch }}
